#!/bin/sh
# Pre-commit hook: run lint before allowing commit

echo "Running make lint..."
make lint
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "Lint failed. Commit aborted."
    exit $RESULT
fi
exit 0
