import json
import logging
import re
from functools import partial
from html import escape as escape_html
from pathlib import Path

from langchain_core.exceptions import OutputParserException
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, SystemMessage
from langchain_core.runnables import Runnable
from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import CompiledStateGraph
from langgraph.prebuilt import ToolNode
from langgraph.types import RetryPolicy
from pydantic import TypeAdapter, ValidationError

from app.agents.analyst.prompts import (
    ANALYST_SYSTEM_PROMPT_TEMPLATE,
    FOLLOW_UP_CONTEXT_TEMPLATE,
    FRONTEND_DESIGNER_PROMPT_TEMPLATE,
    FRONTEND_DESIGNER_SKILL_ID,
    OUTPUT_FORMAT_INSTRUCTIONS,
    PLOTLY_FIGURE_TOKEN,
    STORYTELLER_PROMPT_TEMPLATE,
    STORYTELLER_SKILL_ID,
)
from app.agents.analyst.states import AnalystState, StorytellerOutput
from app.agents.analyst.tools import (
    SUBMIT_TOOL_NAME,
    UPDATE_DASHBOARD_TOOL_NAME,
    build_read_dashboard_tool,
    build_read_figure_tool,
    build_submit_hypotheses_evidence_tool,
    build_update_dashboard_html_tool,
)
from app.agents.common_tools import (
    build_execute_python_script_tool,
    build_list_available_skills_tool,
    build_read_skill_instructions_tool,
)

logger = logging.getLogger(__name__)


STORYTELLER_OUTPUT_METHODS = {
    "deepseek-v4-flash": "json_mode",  # json_schema and forced tool calls are rejected
}
STORYTELLER_MAX_ATTEMPTS = 3


def _format_data_type(data_type) -> str:
    if isinstance(data_type, list):
        return ", ".join(str(dt) for dt in data_type)
    return str(data_type or "unknown")


def _strip_chart_figures(artifact: dict) -> dict:
    """Return a copy of an artifact with the heavy `figure` payloads removed.

    Used when serializing hypotheses_evidence or narrative into an LLM prompt so the
    model never has to process large Plotly JSON.
    """
    charts = artifact.get("charts")
    if not isinstance(charts, list):
        return artifact
    return {
        **artifact,
        "charts": [
            {k: v for k, v in chart.items() if k != "figure"}
            for chart in charts
            if isinstance(chart, dict)
        ],
    }


def _strip_markdown_fences(content: str) -> str:
    """Remove a surrounding markdown code fence e.g. ```html ... ```."""
    content = content.strip()
    if not content.startswith("```"):
        return content

    lines = content.splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].startswith("```"):
        lines = lines[:-1]
    return "\n".join(lines).strip()


def _inject_figures(html: str, narrative: dict) -> str:
    """Replace chart tokens with declarative references to saved figure files.

    Placeholder token generated by frontend designer is replaced with a <div> that has a data-plotly-figure attribute
    This is done by: __PLOTLY_FIGURE_0_ -> Extract index: 0 -> <div id ="plotly-0" data-plotly-figure="fig_0.json"></div>
    """
    charts = narrative.get("charts", [])

    def repl(match: re.Match) -> str:
        idx = int(match.group(1))
        if idx < 0 or idx >= len(charts):
            logger.warning(
                "frontend_designer_invalid_figure_token index=%d chart_count=%d",
                idx,
                len(charts),
            )
            return ""
        chart = charts[idx]
        if not isinstance(chart, dict):
            return ""

        figure_path = chart.get("figure") or ""
        figure_reference = Path(str(figure_path)).name
        if not figure_reference:
            logger.warning("chart %s has no saved figure reference", idx)
            return ""

        safe_reference = escape_html(figure_reference, quote=True)
        return f'<div id="plotly-{idx}" data-plotly-figure="{safe_reference}"></div>'

    return PLOTLY_FIGURE_TOKEN.sub(repl, html)


def form_analyst_system_prompt(state: AnalystState) -> str:
    system_prompt = ANALYST_SYSTEM_PROMPT_TEMPLATE.format(
        dataset_path=state["dataset_path"],
        data_type=_format_data_type(state.get("profile", {}).get("data_type")),
        figures_dir=state["figures_dir"],
    )

    sections = []
    if state.get("hypotheses_evidence"):
        sections.append(
            "Hypotheses and evidence:\n"
            + json.dumps(_strip_chart_figures(state["hypotheses_evidence"]), indent=2)
        )
    if state.get("narrative"):
        sections.append(
            "Narrative:\n"
            + json.dumps(_strip_chart_figures(state["narrative"]), indent=2)
        )
    if state.get("dashboard_path"):
        sections.append(
            "There is an existing dashboard HTML from a previous analysis. "
            f"It is saved at: {state['dashboard_path']}. "
            "You can read its contents with the `read_dashboard` tool, "
            "passing the dashboard path above."
        )

    if len(sections) > 0:
        follow_up_context = FOLLOW_UP_CONTEXT_TEMPLATE.format(
            context="\n\n".join(sections)
        )
        return f"{system_prompt}\n\n{follow_up_context}"
    else:
        return system_prompt


def analyst_node(
    state: AnalystState,
    model: BaseChatModel,
) -> dict:
    """Invoke the analyst LLM with dataset context and category prefixed as system prompt."""

    system_prompt = form_analyst_system_prompt(state)
    all_messages = [SystemMessage(content=system_prompt)] + list(state["messages"])
    response = model.invoke(all_messages)

    logger.debug(
        "analyst_response content=%r tool_calls=%s",
        response.content,
        [
            {"name": tc.get("name"), "args": tc.get("args")}
            for tc in getattr(response, "tool_calls", [])
        ],
    )

    return {
        "messages": [response],
        "llm_calls": state["llm_calls"] + 1,
    }


def parse_analyst_output_node(state: AnalystState) -> dict:
    """Extract the submitted hypotheses_evidence from the submit tool call."""
    last = state["messages"][-1]
    for tool_call in getattr(last, "tool_calls", []):
        if tool_call.get("name") == SUBMIT_TOOL_NAME:
            args = tool_call.get("args", {}) or {}
            hypotheses_evidence = args.get("hypotheses_evidence", args)
            return {
                "hypotheses_evidence": hypotheses_evidence,
                "artifact_action": "analysis",
            }
    raise ValueError("No valid submit_hypotheses_evidence tool call found")


def parse_dashboard_output_node(state: AnalystState) -> dict:
    """Extract the edited dashboard HTML from the update_dashboard_html tool call."""
    last = state["messages"][-1]
    for tool_call in getattr(last, "tool_calls", []):
        if tool_call.get("name") == UPDATE_DASHBOARD_TOOL_NAME:
            args = tool_call.get("args", {}) or {}
            return {
                "dashboard_html": args.get("dashboard_html", args),
                "artifact_action": "dashboard_edit",
            }
    raise ValueError("No valid update_dashboard_html tool call found")


def response_node(state: AnalystState) -> dict:
    """Produce the single clean assistant response for every terminal path."""
    action = state.get("artifact_action")
    last_message = state["messages"][-1]

    # If analyst generates hypotheses evidence, this will get routed all the way to
    # dashboard generation in the graph.
    if action == "analysis":
        message = "I generated the dashboard from the analysis."
    # When analyst use the dashboard edit tool, this default message will be returned to the user.
    elif action == "dashboard_edit":
        message = "The dashboard has been updated."
    # When analyst generates a direct response in its final message, return the message directly
    # or when the analyst has exhausted its llm calls, return a default message to the user.
    else:
        content = str(last_message.content or "").strip()
        has_tool_calls = bool(getattr(last_message, "tool_calls", []))
        message = (
            content
            if content and not has_tool_calls
            else (
                "I couldn't complete the analysis within the available processing budget. "
                "Please try again with a more focused question."
            )
        )

    is_existing_clean_response = (
        isinstance(last_message, AIMessage)
        and not getattr(last_message, "tool_calls", [])
        and str(last_message.content or "").strip() == message
    )
    return (
        {} if is_existing_clean_response else {"messages": [AIMessage(content=message)]}
    )


def retry_node(_state: AnalystState) -> dict:
    """Prompt the analyst to continue when it returned an empty reply."""
    return {
        "messages": [
            SystemMessage(
                content=(
                    "You did not produce a usable response. Continue your analysis and "
                    f"submit your final insights via the `{SUBMIT_TOOL_NAME}` tool."
                )
            )
        ]
    }


def should_continue(state: AnalystState) -> str:
    """Route to tools/retry while analysing, to a terminal node when done, or END."""
    last_message = state["messages"][-1]
    tool_names = {tc.get("name") for tc in getattr(last_message, "tool_calls", [])}

    # Final signals are checked before the budget so a finished artifact is never
    # discarded on exhaustion.
    if UPDATE_DASHBOARD_TOOL_NAME in tool_names:
        return "finalize_dashboard"
    if SUBMIT_TOOL_NAME in tool_names:
        return "parse"

    # The analyst requested further tools.
    if tool_names:
        return (
            "response"
            if state["llm_calls"] >= state["max_llm_calls"]
            else "analyst_tools"
        )

    # No tools: a non-empty reply is a direct conversational answer.
    if (last_message.content or "").strip():
        return "response"

    # Empty content: get the model to continue instead of silently ending.
    return "response" if state["llm_calls"] >= state["max_llm_calls"] else "retry"


def with_storyteller_output(model: BaseChatModel) -> Runnable:
    """Bind StorytellerOutput with the model's supported structured-output method."""
    method = STORYTELLER_OUTPUT_METHODS.get(getattr(model, "model_name", None))
    if method is None:
        return model.with_structured_output(StorytellerOutput)
    return model.with_structured_output(StorytellerOutput, method=method)


def _invoke_storyteller(model: BaseChatModel, messages: list) -> StorytellerOutput:
    """Invoke the storyteller and validate its output, retrying malformed responses.

    The retry lives here because RetryPolicy does not retry ValueError, and both
    pydantic's ValidationError and OutputParserException are ValueErrors.
    """
    for attempt in range(1, STORYTELLER_MAX_ATTEMPTS + 1):
        try:
            return TypeAdapter(StorytellerOutput).validate_python(
                model.invoke(messages)
            )
        except (ValidationError, OutputParserException) as exc:
            if attempt == STORYTELLER_MAX_ATTEMPTS:
                raise
            logger.warning(
                "storyteller_invalid_output attempt=%d/%d error=%s",
                attempt,
                STORYTELLER_MAX_ATTEMPTS,
                exc,
            )


def storyteller_node(
    state: AnalystState,
    model: BaseChatModel,
    skills_dir: Path,
) -> dict:
    """Generate a structured narrative from the analyst's hypotheses and evidence."""
    read_skill_instructions = build_read_skill_instructions_tool(skills_dir)
    skill_instructions = read_skill_instructions.invoke(
        {"skill_name": STORYTELLER_SKILL_ID}
    )
    system_prompt = STORYTELLER_PROMPT_TEMPLATE.format(
        skill_instructions=skill_instructions
    )
    hypotheses_evidence = json.dumps(
        _strip_chart_figures(state["hypotheses_evidence"]), indent=2
    )

    all_messages = [
        SystemMessage(content=system_prompt),
        SystemMessage(content=hypotheses_evidence),
    ]
    output = _invoke_storyteller(model, all_messages)

    charts = [
        {
            "title": chart.get("title", ""),
            "description": chart.get("description", ""),
            "figure": chart.get("figure", ""),
        }
        for chart in state["hypotheses_evidence"].get("charts", [])
    ]
    narrative = {
        "central_question": output["central_question"],
        "slides": output["slides"],
        "charts": charts,
    }
    return {"narrative": narrative}


def frontend_designer_node(
    state: AnalystState,
    model: BaseChatModel,
    skills_dir: Path,
) -> dict:
    """Generate reference-based dashboard HTML from the narrative and its figures."""
    read_skill_instructions = build_read_skill_instructions_tool(skills_dir)
    skill_instructions = read_skill_instructions.invoke(
        {"skill_name": FRONTEND_DESIGNER_SKILL_ID}
    )
    system_prompt = FRONTEND_DESIGNER_PROMPT_TEMPLATE.format(
        skill_instructions=skill_instructions
    )

    # Remove the heavy plotly figures prior to LLM calls
    narrative = json.dumps(_strip_chart_figures(state["narrative"]), indent=2)

    all_messages = [
        SystemMessage(content=system_prompt),
        SystemMessage(content=narrative),
    ]
    response = model.invoke(all_messages)

    response_content = str(response.content)
    logger.debug(
        "frontend_designer_response output_chars=%d preview=%r",
        len(response_content),
        response_content[:1000],
    )
    dashboard_html = _strip_markdown_fences(response_content)
    dashboard_html = _inject_figures(dashboard_html, state["narrative"])
    return {"dashboard_html": dashboard_html}


def build_analyst_graph(
    skills_dir: Path,
    model: BaseChatModel,
    interrupt_after: list[str] | None = None,
) -> CompiledStateGraph:
    """Build and compile the analyst LangGraph.

    ``interrupt_after`` is useful for stage-level tests and evals that need to
    inspect an intermediate artifact without invoking downstream builder nodes.
    Normal application callers should leave it unset.
    """
    list_available_skills = build_list_available_skills_tool(skills_dir)
    read_skill_instructions = build_read_skill_instructions_tool(
        skills_dir,
        output_format_instructions=OUTPUT_FORMAT_INSTRUCTIONS,
    )
    execute_python_script = build_execute_python_script_tool()
    read_dashboard = build_read_dashboard_tool()
    read_figure = build_read_figure_tool()

    tools = [
        list_available_skills,
        read_skill_instructions,
        execute_python_script,
        read_dashboard,
        read_figure,
    ]
    tool_node = ToolNode(tools)
    bound_model = model.bind_tools(
        [
            *tools,
            build_submit_hypotheses_evidence_tool(),
            build_update_dashboard_html_tool(),
        ]
    )

    analyst_node_fn = partial(analyst_node, model=bound_model)
    storyteller_node_fn = partial(
        storyteller_node,
        model=with_storyteller_output(model),
        skills_dir=skills_dir,
    )
    frontend_designer_node_fn = partial(
        frontend_designer_node,
        model=model,
        skills_dir=skills_dir,
    )

    workflow = StateGraph(AnalystState)

    workflow.add_node("analyst", analyst_node_fn, retry_policy=RetryPolicy())
    workflow.add_node("analyst_tools", tool_node)
    workflow.add_node("retry", retry_node)
    workflow.add_node("parse", parse_analyst_output_node)
    workflow.add_node("parse_dashboard", parse_dashboard_output_node)
    workflow.add_node("response", response_node)
    workflow.add_node("storyteller", storyteller_node_fn, retry_policy=RetryPolicy())
    workflow.add_node(
        "frontend_designer",
        frontend_designer_node_fn,
        retry_policy=RetryPolicy(),
    )

    workflow.add_edge(START, "analyst")
    workflow.add_conditional_edges(
        "analyst",
        should_continue,
        {
            "analyst_tools": "analyst_tools",
            "parse": "parse",
            "finalize_dashboard": "parse_dashboard",
            "response": "response",
            "retry": "retry",
        },
    )
    workflow.add_edge("analyst_tools", "analyst")
    workflow.add_edge("retry", "analyst")
    workflow.add_edge("parse", "storyteller")
    workflow.add_edge("parse_dashboard", "response")
    workflow.add_edge("storyteller", "frontend_designer")
    workflow.add_edge("frontend_designer", "response")
    workflow.add_edge("response", END)

    return workflow.compile(interrupt_after=interrupt_after)
